### ISSUE TITLE
Argon4 browser reports as Safari

### ISSUE THREAD

**Issue by that-ben** [argonjs/argon#31]
Argon4 browser reports as Safari and this is somewhat of a problem, because some server-side scripts (PHP, ASP or Java) might want to customize their output to the browser depending on the user-agent, so it needs to say something like: Argon4 or Argon version 4.0 or something standard like that.  This may also be seen as unethical that Argon4 reports as Safari for the sole reason it is not exactly Safari.

**Comment by speigg** [comment]
Hi @that-ben, not sure what you mean. The Argon4 browser reports the following as the user agent string: 
```Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A403 Argon```

**Comment by that-ben** [comment]
Not according to one of those sites: http://detectmybrowser.com/

**Comment by speigg** [comment]
Try this one: https://www.whatismybrowser.com/detect/what-is-my-user-agent

**Comment by that-ben** [comment]
Alright, somehow, the first result in Google proved to be a bad one, but I must admit, the problem is that all of them assume it's Safari just by reading iPhone in the user agent, but I see what you mean, it's written Argon at the end of the string, so that should suffice to detect it using server-side scripting.  Thanks.  Let's close this false issue :)
