### ISSUE TITLE
Please fix examples that are not working

### ISSUE THREAD

**Issue by that-ben** [argonjs/argon#33]
This example does not work on iOS, all values stay at zero and no GeoTracking is done.  http://argonjs.io/samples/code/geopose/index.html

![asdsd](https://cloud.githubusercontent.com/assets/13210399/18731478/1fb097ec-802a-11e6-9450-9ec91cee8a8c.jpg)

**Comment by that-ben** [comment]
Well, it turns out turning on the localization services is not enough.  It also needs one or more of these turned on to work under SYSTEM SERVICES (still under LOCALIZATION SERVICES) / not entirely sure exactly which of those, but it's one of those that unlocked the functionality:

- Cell Network Search
- Compass calibration
- Wi-Fi Networking

Sorry for disturbing, it works great :)

**Comment by speigg** [comment]
It's the compass calibration setting. We do need to detect this and alert the user as to how to correct it.

**Comment by that-ben** [comment]
Yes please, I searched for half an hour hahaha... I feel so ashamed.
