### ISSUE TITLE
The Geopose example needs to set the altitude for the cesium entities.

### ISSUE THREAD

**Issue by colinfizgig** [argonjs/argon#36]
Currently the geopose sample for Argonjs does not set an altitude for the gatech cesium entity.  This works but it reports a false distance because it defaults to sea level if no altitude is entered. This also causes the buzz cube to be located below ground.

**Comment by blairmacintyre** [comment]
Please re-open this over on the right repo (samples).  Would be great if you can suggest an altitude to use.
