### ISSUE TITLE
Argon 4 App code 

### ISSUE THREAD

**Issue by estudioalfa** [argonjs/argon#39]
Hello,

Can we get the argon4 browser app code?

Thanks in advance!

**Comment by blairmacintyre** [comment]
Hi,

We haven't released it yet, but we are planning to.  Very likely after the next release, when we have time to do finally tidying and cleanup.

Out of curiosity, what is your interest?

**Comment by estudioalfa** [comment]
Hi!

Thanks for your quick response!

We are developing an app for a customer 1Q next year and it could help us to do it faster and with a better result. 

Regards

**Comment by blairmacintyre** [comment]
Ok.  I'm not sure we'll get the source code released before the end of this year.  We'll post something to the slack when we do.  FYI, the app is written mostly in Javascript, using the NativeScript software to turn it into an app.

**Comment by estudioalfa** [comment]
Nice! And using JavaScript it awesome for us! 

Thanks!

**Comment by blairmacintyre** [comment]
Great.  Would love to learn more about your app.  Are you creating an iOS AR app for someone, and want to leverage web-tech rather than do it natively?

**Comment by estudioalfa** [comment]
Hi!

We are web developers experienced in SDKs like Appcelerator and Phonegap. That's why using a solution like ARGON based javascript is great for us.

Next year we will develop an AR app and we preffer to use javascript coding rather than native because of the learning curve.

**Comment by blairmacintyre** [comment]
One thing we've talked about a lot, but haven't had a chance to really look at, is how to restructure the source to make it easy to "build an app" with it (e.g., to replace the UI, hide the "browser" part, and embed the web code inside there).   Might be something worth looking at and considering, once the code is out.

**Comment by estudioalfa** [comment]
We would love to help you on looking at your code to give you our opinion as app developers using javascript frameworks with no experience on native coding.

**Comment by blairmacintyre** [comment]
We'll be happy to have it, once we are ready to open it up.  I'm working on it!

**Comment by estudioalfa** [comment]
Hello @blairmacintyre!

Did you managed to release the argon4 browser app code?

**Comment by blairmacintyre** [comment]
Quite some time ago. It’s in the argon-app repo
