### ISSUE TITLE
Error - Cannot find module "."

### ISSUE THREAD

**Issue by ashwathan** [argonjs/argon#42]
Hi,

I'm trying to integrate argonjs library in my ionic 2 app. I followed the method which is given in http://docs.argonjs.io/start/setup/. 
I installed argonjs using npm `npm install @argonjs/argon@^1.0`. 
Imported in my ts file, `import * as Argon from '@argonjs/argon'`.
I'm getting `Cannot find module "."` error when I called init method (Argon.init()).

I am using,
  Ionic Framework: 2.0.0-rc.5
  Ionic Native: 2.2.11
  Ionic App Scripts: 1.0.0
  Angular Core: 2.2.1
  Angular Compiler CLI: 2.2.1
  Node: 6.9.1
  OS Platform: Windows 7

tsconfig.json:
    {
        "compilerOptions": {
            "allowSyntheticDefaultImports": true,
            "declaration": false,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "lib": [
            "dom",
            "es2015"
            ],
            "module": "es2015",
            "moduleResolution": "node",
            "sourceMap": true,
            "target": "es5"
        },
        "include": [
            "src/**/*.ts"
        ],
        "exclude": [
            "node_modules"
        ],
        "compileOnSave": false,
        "atom": {
            "rewriteTsconfig": false
        }
    }

Error message:
 **Runtime Error**
   Cannot find module "."
 **Stack**
 **Error**: Cannot find module "."
    at webpackMissingModule (http://localhost:8100/build/main.js:97112:3910)
    at http://localhost:8100/build/main.js:97112:3988
    at Object.<anonymous> (http://localhost:8100/build/main.js:97112:4534)
    at Object.<anonymous> (http://localhost:8100/build/main.js:118068:30)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:55840:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:118078:75)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:85858:73)

Please let me know what I'm doing wrong here...

**Comment by aneymond** [comment]
Same problem for me, in IONIC.

npm install @argonjs/argon@^1.0.
In my TS file : import * as Argon from '@argonjs/argon'.
I'm getting "Cannot find module "." error" when I called anything about Argon.

init method Argon.init() 
or anything else like : 
const Cesium = Argon.Cesium
or 
console.log(Argon);

Same error message.

Thanks for your help

**Comment by speigg** [comment]
This looks like a problem with your webpack configuration. Is any other package in your `node_modules` directory loading correctly? Can you share your webpack config?

**Comment by aneymond** [comment]
Hi, thank you for your answer.
Everything in my node_modules directory is loading correctly.
With the exception of that, everything works well, and seems to be loaded, as long as I do not use "Argon" object.

how can can i share webpack config with you ? 
Actually, I simply use "webpack": "^1.12.9", in my package.json, in an ionic context.

Thanks.

**Comment by speigg** [comment]
I've been able to reproduce this problem, and am looking for a solution.

**Comment by speigg** [comment]
Okay, pretty sure this is the source of the problem https://github.com/systemjs/builder/issues/734
I'll have to try rebuilding argon.js with this updated version of the systemjs builder

**Comment by aneymond** [comment]
You're probably right. That's exactly the trace i get. 
Let us know when you will be able to rebuild with this fix.
Many thanks.

**Comment by speigg** [comment]
It seems that the fix has not yet made it into jspm-cli. Once jspm pulls in this fix, a future release of argon.js will work for you. In the meantime, please try this as a workaround:

Load argon.js manually via a script tag in your html:

```html
<script src="node_modules/@argonjs/argon/dist/argon.js'></script>
```

And then, instead of importing argon via a `import` statement, add the following line to your module (where you would normally use `import`):
```
/// <reference types="@argonjs/argon" />
```

After doing this, you should be able to use the @argon/argonjs package via a global `Argon` variable. Let me know if this works for you!

**Comment by speigg** [comment]
Actually, Typescript may still complain with this workaround. You may just have to declare the Argon variable as type `any` if you want to load argon.js via a script element. The next release of Typescript should allow you to use UMD globals within a module.

**Comment by ashwathan** [comment]
@speigg Thank you for your answer,

I have added argonJS & threeJS scripts tags in my html.
`<script src="resources/lib/three/three.min.js"></script>
 <script src="resources/lib/argon.js"></script>`

JS file is getting loaded but I'm getting following error (when I added script tag for argonJS).
`Uncaught Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (ng_module_resolver.js:31)
    at CompileMetadataResolver._loadNgModuleMetadata (metadata_resolver.js:334)
    at CompileMetadataResolver.loadNgModuleMetadata (metadata_resolver.js:313)
    at RuntimeCompiler._loadModules (runtime_compiler.js:99)
    at RuntimeCompiler._compileModuleAndComponents (runtime_compiler.js:69)
    at RuntimeCompiler.compileModuleAsync (runtime_compiler.js:59)
    at PlatformRef_._bootstrapModuleWithZone (application_ref.js:302)
    at PlatformRef_.bootstrapModule (application_ref.js:284)
    at Object.<anonymous> (main.ts:5)
    at __webpack_require__ (bootstrap a30429e…:19)`

![console_log](https://cloud.githubusercontent.com/assets/11681176/22135731/15d0011a-def6-11e6-8740-ab1a89e944ce.jpg)

Thank you

**Comment by speigg** [comment]
These errors have nothing to do with Argon. Looks like angular errors. Does this happen just when you load argon.js in a script element, or are you initializing it too? Is the Argon global being created correctly?

**Comment by ashwathan** [comment]
@speigg 
It happened only when I added argon.js script tag. Before this my app was working normal.

**Comment by blairmacintyre** [comment]
Just so you know, I don't think we have ever tried to use argon.js in a cordova app, so we've never run into these kinds of issues.  Have you tried to rebuild the argon.js files yourself, and see what it takes to make it work with Cordova?

**Comment by ashwathan** [comment]
There is no error after loading argonjs dynamically.

Thank you

**Comment by speigg** [comment]
> There is no error after loading argonjs dynamically.
>
> Thank you

Glad you resolved the errors! I'm curious though, what do you mean by "loading argonjs dynamically"?

**Comment by ashwathan** [comment]
Instead of script tag, http://stackoverflow.com/questions/21294/dynamically-load-a-javascript-file
   `var head = document.getElementsByTagName('head')[0];
   var script = document.createElement('script');
   script.type = 'text/javascript';
   script.src = url;
   script.onload = callback;
   head.appendChild(script);`

**Comment by speigg** [comment]
@ashwathan I suspected that is what you meant, but I'm not sure why that would make a difference. Strange.

**Comment by shukieshah** [comment]
Issue Resolved
