### ISSUE TITLE
npm run build command error

### ISSUE THREAD

**Issue by hanbim520** [argonjs/argon#46]
> jspm build src/argon.ts .tmp/argon-build.js --node --format umd --global-name Argon --skip-source-maps && derequire .tmp/argon-build.js > dist/argon.core.js

     Creating the single-file build for src/argon.ts...

err  Error on translate for src/argon.ts at file:///Users/abc/work/argon/src/argon.ts
  (SystemJS) ENOENT: no such file or directory, open '/Users/abc/work/argon/jspm_packages/npm/systemjs-plugin-babel@0.0.17.json'
  Error: ENOENT: no such file or directory, open '/Users/abc/work/argon/jspm_packages/npm/systemjs-plugin-babel@0.0.17.json'
  Error loading /Users/abc/work/argon/jspm_packages/npm/systemjs-plugin-babel@0.0.17.json
  Unable to load transpiler to transpile /Users/abc/work/argon/src/argon.ts

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "build:core"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @argonjs/argon@1.1.2 build:core: `jspm build src/argon.ts .tmp/argon-build.js --node --format umd --global-name Argon --skip-source-maps && derequire .tmp/argon-build.js > dist/argon.core.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @argonjs/argon@1.1.2 build:core script 'jspm build src/argon.ts .tmp/argon-build.js --node --format umd --global-name Argon --skip-source-maps && derequire .tmp/argon-build.js > dist/argon.core.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @argonjs/argon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm build src/argon.ts .tmp/argon-build.js --node --format umd --global-name Argon --skip-source-maps && derequire .tmp/argon-build.js > dist/argon.core.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @argonjs/argon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @argonjs/argon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abc/work/argon/npm-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @argonjs/argon@1.1.2 prebuild: `npm run build:core && npm run build:browser && uglifyjs dist/argon.js -b -o dist/argon.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @argonjs/argon@1.1.2 prebuild script 'npm run build:core && npm run build:browser && uglifyjs dist/argon.js -b -o dist/argon.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @argonjs/argon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:core && npm run build:browser && uglifyjs dist/argon.js -b -o dist/argon.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @argonjs/argon
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @argonjs/argon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abc/work/argon/npm-debug.log

**Comment by speigg** [comment]
Did you do `jspm install` first?

**Comment by dboots** [comment]
I had to run `jspm install plugin-babel` and that installed the missing dependancy. I have a feeling that it is due to me using version 2.14.3 of npm. Another solution could be to update your npm via `npm install npm@latest -g`, but that isn't an option for me.

**Comment by speigg** [comment]
Hmm, yeah, occasionally the version of node/npm can cause problems. However, I believe this issue is fixed in the develop branch. There should no longer be a dependency to plugin-babel.

**Comment by hanbim520** [comment]
Oh,sorry.I transferred the project to my colleague, and I did not follow up on the follow-up work. I am now mainly in the development of this piece of the game, in my github now do some recognition of things, is just beginning, the code has not yet collated. In our country, access to foreign websites will be limited, install some software will need to cross the national firewall can.

**Comment by shukieshah** [comment]
Issue Resolved
