### ISSUE TITLE
Please fix the npm install issues

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon#5]
Fresh install, gives these warnings:
npm WARN package.json argon@0.2.0-alpha No repository field.
npm WARN package.json argon@0.2.0-alpha No license field.
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

First two are easy to fix.  For the other two:  can you edit the package file to give a less explicit version of those packages, if new version work?

**Comment by Rohanrk** [comment]
Have we opened on issue on their repo about this?

**Comment by Rohanrk** [comment]
Fixed the package.json file which fixes the first 2 warnings. The last warning doesn't appear right now so I think the dependency was updated.
