### ISSUE TITLE
Vuforia PGP Encryptor is not working

### ISSUE THREAD

**Issue by bobolovecat** [argonjs/argon#50]
It worked well yesterday but today it reported error in console:
Failed to load resource: the server responded with a status of 502 (Proxy Error)
Fetch API cannot load https://pgp.mit.edu/pks/lookup?op=get&options=mr&search=secure%40argonjs.io. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.argonjs.io' is therefore not allowed access. The response had HTTP status code 502.
Uncaught (in promise) TypeError: Failed to fetch(…)

**Comment by blairmacintyre** [comment]
Weird.  I don't see this at first (in Chrome, Safari, or Firefox) but now I see it in Safari.  What browser are you seeing it in?

**Comment by bobolovecat** [comment]
@blairmacintyre
it reported error in console in Chrome and Firefox in my computer

**Comment by blairmacintyre** [comment]
Hmmm.  working for me (although painfully slow on Chrome, wow).  My Chrome says it's up to date, Firefox is too.

I'm on the MacOS 10.12.3, you?

**Comment by bobolovecat** [comment]
@blairmacintyre 
Oh, I just clear my cookies and it works well now, thx~

**Comment by blairmacintyre** [comment]
aha!  Great, I'll close this.
