### ISSUE TITLE
Problems with revised Vuforia API

### ISSUE THREAD

**Issue by ammulder** [argonjs/argon#63]
When running the Vuforia sample, I get a number of deprecation warnings: createDataSet, subscribeToEntityById, and getEntityPose

I'm having trouble figuring out the "correct" usage.  Here's what I tried:
```
this.app.vuforia.init(...)
.then((api) => {
  this.vuforiaAPI = api;
  return this.vuforiaAPI.objectTracker.createDataSetFromURI("foo.xml");
}).then((dataSetId) => {
  this.vuforiaDataSetId = dataSetId;
  return this.vuforiaAPI.objectTracker.loadDataSet(dataSetId);
}).then((trackables) => {
  return this.app.context.subscribe(trackables["foo"].id);
}).then((targetEntity) => {
 ...
}).catch(...);
```

And I get this error:
```
Request 'ar.vuforia.objectTrackerLoadDataSet' rejected with reason:
Unable to handle message ar.vuforia.objectTrackerLoadDataSet
```
with an alert that says
```
No handlers are available for topic
ar.vuforia.objectTrackerLoadDataSet
```

Any advice?

**Comment by speigg** [comment]
Ah, this is a backwards compatibility bug I missed. Can you use the deprecated API for now as a workaround? We'll make sure that both APIs continue to work (once this bug is fixed), but new features will be exposed in the new API going forward.
