### ISSUE TITLE
Misc Non-Fatal Errors in Vuforia

### ISSUE THREAD

**Issue by ammulder** [argonjs/argon#64]
Running the Vuforia sample on an iPad Pro, I get all of the following in the console.  None of it stops anything from working.
```
Unhandled Error: ReferenceError: Can't find variable: __ARGON_PORT__ (undefined: 1)
...
Recalculating device params.
User agent: Mozilla/5.0 (iPad; ...
Pixel width: 2048
Pixel height: 1536
No DPDB device match.
New device parameters:
null
Failed to recalculate device parameters
...
Unhandled Error: TypeError: undefined is not an object (evaluating 'originalDescGet.apply') (undefined: 2802)
...
Invalid timestamps detected.  Time step between successive gyroscope sensor samples is very small or not monotonic
```

That last one I've seen a few times, but it doesn't happen on every run, and I haven't seen it more than once per run.  (This latest time I noticed that my lighting stopped working, and the light is positioned in my render event listener, so it's possible the listener stopped working after the not monotonic error, but I haven't done much diagnosis on the lighting thing so it might also be unrelated.)

**Comment by speigg** [comment]
`Unhandled Error: ReferenceError: Can't find variable: __ARGON_PORT__ (undefined: 1)`

Just fixed this. Will be gone in next release of the browser. 

It looks like the rest of those errors are coming from https://github.com/googlevr/webvr-polyfill (which is built into argon.js) so there isn't much I can do about that.
