### ISSUE TITLE
Track Multiple Vuforia Markers

### ISSUE THREAD

**Issue by emorling** [argonjs/argon#82]
Is it possible to track multiple Vuforia markers? I tried, but it seems to only track one at a time?

**Comment by blairmacintyre** [comment]
Hmmmm.   I thought we added this.  It is in the Argon4 app source, but doesn't appear to be exposed through argon.js.  We are in the process of releasing the next version right now (as in, quite literally, right now), will look into this when that's done.

**Comment by kimberlysiva** [comment]
Complete
