### ISSUE TITLE
distance suddenly changed 

### ISSUE THREAD

**Issue by ShahriarVelayat** [argonjs/argon#90]
Hi 
I'm new with argon.
I changed the sample code and put a  location Instead GA location when I opened the page in argon browser it shows me the distance 130 m and show buzz box correctly and it's correct but suddenly changed to 1330 m and not show buzz box and it's not correct and never show correct distance again.
what should I do? 
is this a bug in argon??

**Comment by blairmacintyre** [comment]
Argon uses your phones location service which can jump around quite a bit. Are you inside with poor location?

Also, there is a race condition bug in the current version that sometimes causes the initial position to jump.  If you can try the develop branch (if you are pulling from github) or the "next" version on mom (if you are pulling from there) and see if that helps.

**Comment by ShahriarVelayat** [comment]
thanks for your reply
I'm not inside when I came closer to target it has lost and the distance change to 1333 m.
when the page opened the distance is 572 m.
what is mom" in this "the "next" version on mom"???

**Comment by ShahriarVelayat** [comment]
this is my location 35.707707 lat ,51.441136 long and the target is in 110 m in coordinate 35.707025 lat , 51.440306 long but the argon app shows me the distance 1231.42.

**Comment by ShahriarVelayat** [comment]
[in this picture](http://gshub.ir/screenshots/Screenshot_20170806-165028.png)
 this picture you can see the buzz box far far away from my screen, a little point in the bottom of the picture .
thanks again for your help.

**Comment by blairmacintyre** [comment]
Re: mom was my iPhone helpfully fixing "npm" without me noticing.

The first time you run at an a new location it will reset after a bit after it fetches the elevation data.  The buzz box seems ok, perhaps.  Is the other box reasonable?  At that distance it would be pretty small too.

I assume you tried reloading the page?

**Comment by ShahriarVelayat** [comment]
:-) 
 I used @argonjs/argon@1.4.0-5 but I have the same problem it shows distance 90 m the changed to 1333.
I didn't reload the page.
At the first Time when I opened the paged everything is correct and the BUZZ CUBE is correctly shown in front of me but after a moment the box moves down on the ground and the distance isn't correct.

**Comment by ShahriarVelayat** [comment]
[see this please](http://gshub.ir/screenshots/SCR_20170806_190945.mp4)

**Comment by blairmacintyre** [comment]
The distance is changing in the video when the location reports go from being unknown (the web app doesn’t have a location immediately) to there being location reports received (from the OS, to Argon, to and then passed into the web page);  when it says “Unknown” for location, that literally means the location is unknown.  

The distance is larger than you expect because the location your phone thinks it’s at is 35.737616, 51.454628 (not 35.707707, 51.441136).

**Comment by ShahriarVelayat** [comment]
hi 
thanks for your help finally last night I found my mistake
in this line 
 position: Cartesian3.fromDegrees(51.455367,35.737715)
I didn't set height but it needs it 
when I set the height like this
 position: Cartesian3.fromDegrees(51.455367,35.737715,1300)
everything gets correct.
thanks a lot for your help.

**Comment by blairmacintyre** [comment]
Aha, yes.  If you don't set height, we try to set it from the global heightmaps at Mapzen.com .... if they don't have coverage (or are inaccessible) this might be very incorrect (might get set to sea level!)

If you know of good elevation maps, it might be worth making it possible for an app to specify where they get retrieved from.  Or to get mapzen to include them.

**Comment by ShahriarVelayat** [comment]
thanks a lot.
