### ISSUE TITLE
Argon Js dropdown not working with Laravel app.js

### ISSUE THREAD

**Issue by doubleprincez** [argonjs/argon#96]
I tried adding argon.js to my Laravel project but my dropdowns won't work till i remove the js/app.js that makes vue work. Please what is the right way to combine both? Im using a non vue navbar with dropdowns and main content connected to vue

**Comment by blairmacintyre** [comment]
We have not tried to use any of the all-in-one web app toolkits (like vue or react);  both argon.js and vue (or react) probably make some assumptions about how the DOM will be structured, and those aren't playing well together.  It's probably possible to combine them, but I don't quite no how (I've never used vue).  Sorry!

**Comment by doubleprincez** [comment]
I will try to fix it and get back to you. Thanks

**Comment by doubleprincez** [comment]
Im very grateful for your time. I actually got to read alot of articles about it and finally got to fix it when i removed the jquery.min.js cdn connected to it because it has already been included with Argon.js.  Thanks once again
